## sample Deployment.yml for nodejs Zomato application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      name: dm-template
      labels:
        app: dm
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
          
---

apiVersion: v1
kind: Service
metadata:
  name: dm-svc
spec:
  type: NodePort
  selectors:
    app: dm
  ports:
    - port: 80
      targetPort: 80
