## sample Deployment.yml for nodejs Zomato application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      name: zomato-template
      labels:
        app: zomato1
    spec:
      containers:
        - name: cont1
          #image: nikhil74/zomatoapp:v2
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
            #- containerPort: 3000
